[FIX] background-color + convenções + bootstrap
VRI-UFPR/CienciaNaEscola pull request #103
Opened 2023-04-24 11:14 UTC by YuriTobias

2023-04-25 12:33 UTC, EduardoMathiasSouza approved these changes

2023-04-25 13:06 UTC, JulianaZambon approved these changes

2023-04-27 11:59 UTC, IosBonaldi requested changes
- Importações de DateInput, TimeInput e Location foram removidas, mas as referência aos componentes ainda estão lá;
- bg-red (rgba(245, 148, 137, 1)) é o mesmo bg-coral-red (#F59489) já usado em outros componentes. Manter um padrão pode ser conveniente se eventualmente quisermos centralizar essas estilizações.
- bg-munsell (rgba(254, 207, 134, 0.7)) é o mesmo bg-yellow-orange (#FECF86) usado em outros componentes.
- O alpha do padrão RGBA não é feito pra alcançar cores específicas que o RGB não alcança. Alterar a opacidade do componente aumenta a transparência dele e faz com que a cor do mesmo seja afetada pela cor do componente imediatamente abaixo dele (ex: um componente amarelo acima de um vermelho vai ficar laranja). Pode acarretar n problemas que os HEX usados até então não acarretam.

2023-04-28 15:34 UTC, IosBonaldi approved these changes
- Excelente, como sempre 🥳

2023-04-30 19:21 UTC, merged