[ADD] Botões + PopUp Logout
VRI-UFPR/CienciaNaEscola pull request #137
Opened 2023-05-16 23:32 UTC by m-piovesan

- Fix na sidebar da Profile Page (não funcionava o Logout)
-  Implementação dos botões de estatísticas e respostas

2023-05-17 00:52 UTC, JulianaZambon approved these changes

2023-05-19 12:36 UTC, IosBonaldi approved these changes
- Muito bom! 😁
- Não entendi a adição de um arquivo vazio. Qual seria a função do StaticButton?

2023-05-19 12:36 UTC, IosBonaldi commented on src/pages/CreateProtocolPage.jsx
> +                    </div>
```suggestion
                    <div className="col-2 ">
                        <TextButton role="link" hsl={[6, 84, 75]} text="Estatísticas" />
                    </div>
                    <div className="col-2">
                        <TextButton role="link" hsl={[37, 98, 76]} text="Respostas" />
                    </div>
```

- Como são links que não submetem formulário, não cabe type="submit". Já role="link" teoricamente deve ajudar a indexação e entendimento da página pelos navegadores.

2023-05-22 13:12 UTC, YuriTobias approved these changes

2023-05-28 23:12 UTC, IosBonaldi approved these changes

2023-05-29 14:52 UTC, YuriTobias requested changes
- No geral ficou muito bom!
- Com relação a responsividade, embora eu acredite que os botões não devam aparecer na versão mobile, se formos pensar em uma dash responsiva, faz sentido e ficou ótimo assim!
- Só corrigir a questão da div vazia mesmo...

2023-05-29 14:52 UTC, YuriTobias commented on src/pages/CreateProtocolPage.jsx
>                  </div>
```suggestion
                
```
Div vazia...

2023-06-30 14:10 UTC, YuriTobias approved these changes

2023-06-30 14:12 UTC, merged