#126 [FEAT]: Criação do componente de lista suspensa
VRI-UFPR/CienciaNaEscola pull request #138
Opened 2023-05-21 20:50 UTC by j-armenio

** Algumas páginas foram removidas pois estavam dando erro, ignorar as exclusões.

2023-05-22 11:56 UTC, IosBonaldi requested changes
- Muito bom 😀;
- Não entendi o leiaute do Figma, então me abstenho de revisar esse aspecto;
- Remover alterações em ProfilePage e ProtocolPage

2023-05-22 11:56 UTC, IosBonaldi commented on src/components/SelectInput.jsx
> +import React from 'react';
```suggestion
import React from 'react';
```
- Importação não usada;

2023-05-22 11:56 UTC, IosBonaldi commented on src/components/SelectInput.jsx
> +            <div className="row m-0 d-flex justify-content-end">
```suggestion
            <div className="row d-flex justify-content-end m-0">
```
- Convenções;

2023-05-22 13:13 UTC, YuriTobias approved these changes

2023-05-24 00:55 UTC, JulianaZambon approved these changes

2023-05-29 15:09 UTC, YuriTobias requested changes
- No geral está bem funcional e parecido com o layout do figma. Show!
- Só reforçar a remoção/alteração do import desse componente na ProtocolPage;

2023-05-29 15:09 UTC, YuriTobias commented on src/components/SelectInput.jsx
> +                    <select className="form-select select-border-gray rounded-3">
Tu pode adicionar um "border-0" aqui pra remover o borda cinza estática no início... Quando tu clicar vai exibir uma borda azul, creio que tenha como retirar ela também, vou pesquisar...

2023-05-29 15:09 UTC, YuriTobias commented on src/components/SelectInput.jsx
> +                <div className="col-5 px-0 pt-2">
Tomar cuidado com o display dessa div e do label, porque estão ficando em linhas diferentes... Seria interessante mantê-los na mesma linha!

2023-06-23 19:11 UTC, denielzzz approved these changes

2023-06-23 19:12 UTC, JulianaZambon approved these changes

2023-06-23 19:12 UTC, JulianaZambon approved these changes

2023-06-23 19:14 UTC, YuriTobias approved these changes

2023-07-31 13:05 UTC, YuriTobias requested changes
![image](https://github.com/VRI-UFPR/CienciaNaEscola/assets/118993772/ca418c84-d974-458b-ab89-496171260010)
Sugestão :)...

2023-08-17 14:19 UTC, closed without merging

2023-08-17 14:20 UTC, j-armenio commented
Nova branch  criada para lista suspensa.