#81 [FEAT] Revisão página índice de protocolos appdashboard
VRI-UFPR/CienciaNaEscola pull request #154
Opened 2023-06-12 18:37 UTC by j-armenio

2023-06-15 13:09 UTC, IosBonaldi requested changes
![image](https://github.com/VRI-UFPR/CienciaNaEscola/assets/43620413/6ac69cb2-95d0-40b1-9c8c-f4361ce494ec)
- Texto do botão "Criar novo protocolo" extrapolando corpo em visualização mobile;

2023-06-15 13:09 UTC, IosBonaldi commented on src/components/ProtocolCarousel.jsx
> +            <div key={i} className={`h-100 carousel-item${i === 0 ? ' active' : ''}`}>
```suggestion
            <div key={i} className={`carousel-item${i === 0 ? ' active' : ''} h-100`}>
```
- Convenção;

2023-06-15 13:09 UTC, IosBonaldi commented on src/pages/RecentProtocols.jsx
> +            <div className="row m-0 flex-grow-1">
```suggestion
            <div className="row flex-grow-1 m-0">
```
- Convenção;

2023-06-19 18:07 UTC, YuriTobias approved these changes

2023-06-19 18:12 UTC, YuriTobias commented
- O código em si está bem estruturado, bonitinho e bem feito;
- Aparentemente quando você clica em qualquer botão que deveria redirecionar para a visualização do protocolo ele muda o slide;
- As flechas que mudam de slide também estão aparecendo de forma estranha, creio que a ideia seria removê-las, não??

2023-06-19 18:15 UTC, YuriTobias requested changes
- Revisão na página de conversa

2023-09-25 01:17 UTC, closed without merging