163 fix upload button design
VRI-UFPR/CienciaNaEscola pull request #175
Opened 2023-08-07 01:05 UTC by denielzzz

o design não ficou exatamente igual ao da Clara, pois não achei uma maneira bonita de mostrar quando uma imagem tinha sido escolhida corretamente pelo input, mas nada que não de para mudar. ficou assim: 
![image](https://github.com/VRI-UFPR/CienciaNaEscola/assets/127148359/a8079b64-8e6a-424a-a6b1-39db48ad0fe9)
(perdao pelo monte de alterações, eu dei um git pull da main para essa branch :p, eu só realmente alterei o src/components/inputs/answers/ImageInput.jsx)

2023-08-07 09:48 UTC, EduardoMathiasSouza approved these changes
Achei bonitinho o design e tá tudo certo

2023-08-07 13:38 UTC, YuriTobias requested changes
- Ficou excelente! Funcional e segue o layout definido no figma! Parabéns, de verdade!
- Única ressalva mesmo é com relação ao htmlFor que foi alterado :)

2023-08-07 13:38 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +                    <label htmlFor="simpletext" className="control-label color-dark-gray font-barlow fw-medium fs-6 p-0 pb-3">
Esse atributo htmlFor especifica a qual elemento o label está vinculado, certo?! Dito isso, ele deve estar relacionado com o id de algum input, não?! Quando tu mudou aqui pra "simpletext" e manteve o id do input abaixo como "imageinput" ele deixou de ter vínculo com o input :(

2023-08-11 17:39 UTC, JulianaZambon approved these changes

2023-08-23 23:25 UTC, YuriTobias requested changes

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +    }
```suggestion
```
Dá pra adicionar simplesmente ms-2 direto na div :) (eu sei que daí não fica com 10px, mas não precisa ser exatamente igual, sabe?!)

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +                        <div className="button-label d-flex color-dark-gray font-barlow fw-medium fs-6 w-100 p-0 pb-0">
```suggestion
                        <div className="d-flex color-dark-gray font-barlow fw-medium fs-6 w-100 p-0 ms-2">
```

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
```suggestion

    .bg-dark-sky-blue {
        background-color: #91CAD6;
    }

```

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +    }
```suggestion
    .image-input-button {
        width: 41px;
        min-width: 41px;
        height: 41px;
        outline: none;
    }
```

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +                        <button type="button" className="image-input-button" onClick={handleButtonClick}>
```suggestion
                        <button type="button" className="image-input-button d-flex align-items-center justify-content-start border-0 rounded-circle bg-dark-sky-blue p-2" onClick={handleButtonClick}>
```

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +                                <div className="d-flex justify-content-center w-100 bg-grey rounded-4 overflow-hidden">
```suggestion
                                <div className="d-flex justify-content-center rounded-4 overflow-hidden bg-grey w-100">
```

2023-08-23 23:25 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
Ficou excelente, só fiz mais algumas sugestões de correção quanto as convenções :)

2023-08-24 13:15 UTC, YuriTobias requested changes
Alguns updates :)

2023-08-24 13:15 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +    }
```suggestion
```

2023-08-24 13:15 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +                        </button>
```suggestion
                        <RoundedButton
                            hsl={[190, 46, 70]}
                            icon={iconFile}
                            size={41}
                            alt={'Selecionar Arquivo'}
                            onClick={handleButtonClick}
                        />
```

2023-08-24 13:15 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
```suggestion
import RoundedButton from '../../RoundedButton';

```

2023-08-24 13:15 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +                        </button>
Existe esse componente RoundedButton que serve pra fazer exatamente o que tu estava fazendo na "mão" hehe... Ainda estou vendo a possibilidade de melhorar a estilização do button por meio das props, se der vai ficar melhor ainda :)

2023-10-02 12:39 UTC, YuriTobias approved these changes
- Excelente;

2023-10-02 13:15 UTC, merged