[FIX] botão de fechar da sidebar dinâmico em todas as resoluções
VRI-UFPR/CienciaNaEscola pull request #186
Opened 2023-08-13 14:01 UTC by m-piovesan

- Apenas retirei essa class: "d-lg-none" da div do botão de fechar a sidebar, pois a mesma é responsável por remover o elemento em grandes telas, não entendi o motivo de ter sido implementado dessa forma pra ser sincero kkkkkkk

2023-08-16 00:37 UTC, m-piovesan commented
Manos fiz algo que não sei se é o mais correto, mas a princípio está funcionado;
- adicionei algumas características específicas que fazem com que o botão de fechar apareça:
    1 - quando a resolução é pequena (para todas as telas)
    2 - quando a resolução é maior, somente para a tela /home

2023-08-17 11:31 UTC, IosBonaldi requested changes
**Correções necessárias**
- As páginas de visualizar/criar/editar protocolos não mostram o botão fechar em visualização desktop;
**Sugestões prescindíveis**
- Usar o hook de Location pode ser um problema quanto à escabilidade (outras páginas além da HomePage com mesmo comportamento, mudança no caminho dessas rotas, etc). O ideal seria a própria página informar ao componente como deve se comportar. Mas funciona;
- Há componentes do Bootstrap que dispensariam interação direta verificando larguras manualmente. Mas funciona;

2023-08-24 13:25 UTC, YuriTobias approved these changes

2023-08-24 13:25 UTC, YuriTobias commented on src/pages/HomePage.jsx
Top!

2023-08-24 13:25 UTC, YuriTobias commented on src/pages/ProtocolPage.jsx
Top²!

2023-08-24 13:25 UTC, YuriTobias commented on src/pages/CreateProtocolPage.jsx
Top³!

2023-08-24 13:25 UTC, YuriTobias commented on src/components/Sidebar.jsx
Excelente! Ótimo trabalho... Aparentemente tudo faz sentido e funciona conforme esperado! Show xD

2023-08-24 14:55 UTC, IosBonaldi approved these changes

2023-08-24 14:55 UTC, IosBonaldi commented on src/components/Sidebar.jsx
> +                    <div className="container d-flex justify-content-end p-0 erro">
- Adicionar um `${showExitButton ? '' : 'd-lg-none'}` no className dessa div teria tido o mesmo efeito da adição dos listeners via useEffect e eliminaria a necessidade do isMobile (o Bootstrap permite associar displays à breakpoints específicos). Na prática, o comportamento é igual.

2023-08-24 16:44 UTC, m-piovesan commented on src/components/Sidebar.jsx
> +                    <div className="container d-flex justify-content-end p-0 erro">
Será que é melhor eu mudar ou posso dar merge assim mesmo?

2023-08-24 16:59 UTC, IosBonaldi commented on src/components/Sidebar.jsx
> +                    <div className="container d-flex justify-content-end p-0 erro">
Não sei o projeto tem algum padrão/convenção do que seria melhor nesse caso. Como na prática ambos vão funcionar exatamente igual, eu não me oporia a passar assim mesmo (até porque está bem escrito) e deixar pra discutir padronizar tudo de uma maneira ou outra em alguma refatoração geral futura;

2023-08-25 12:54 UTC, merged