173 feat adicionar logos
VRI-UFPR/CienciaNaEscola pull request #193
Opened 2023-08-23 19:31 UTC by eduardaafreitas

2023-08-23 19:42 UTC, IosBonaldi approved these changes

2023-08-24 13:30 UTC, YuriTobias approved these changes
Show!

2023-08-24 13:32 UTC, YuriTobias requested changes
Show! Só corrigir a questão do alt e sucesso :)

2023-08-24 13:32 UTC, YuriTobias commented on src/pages/LoginPage.jsx
> +                    <img className="h-auto w-100" src={logoFA} style={{ maxWidth: '200px' }} />
Ficou faltando adicionar algum "alt" aqui e na linha 116 :)

2023-08-24 19:20 UTC, YuriTobias approved these changes

2023-08-24 19:20 UTC, YuriTobias commented on src/pages/LoginPage.jsx
- Show!

2023-08-28 14:17 UTC, JulianaZambon approved these changes

2023-09-11 21:35 UTC, merged