[FIX] correção dos nomes dos membros na parte inferior da página
VRI-UFPR/CienciaNaEscola pull request #202
Opened 2023-09-17 22:51 UTC by JulianaZambon

- Incluí os nomes dos recém-chegados ao projeto na nossa equipe de membros;
- Editei a parte da rota para poder separar "sobre o PICCE" de "equipe";
- Adicionei o "lorem ipsum" de acordo com o layout padrão do Figma.
- Coloquei os nomes dos membros da equipe na parte inferior da página, logo após o conteúdo sobre o PICCE.

- Dúvida: Deixamos os nomes dos membros separados por linhas, como em tópicos mesmo?

2023-09-18 11:15 UTC, etodt commented
> * Incluí os nomes dos recém-chegados ao projeto na nossa equipe de membros;
> 
>     * Editei a parte da rota para poder separar "sobre o PICCE" de "equipe";
> 
>     * Adicionei o "lorem ipsum" de acordo com o layout padrão do Figma.
> 
>     * Coloquei os nomes dos membros da equipe na parte inferior da página, logo após o conteúdo sobre o PICCE.
> 
>     * Dúvida: Deixamos os nomes dos membros separados por linhas, como em tópicos mesmo?

Sobre os nomes, que tal colocar em bloco, como "Clara; Daniel; Eduarda; Eduardo; Eduardo; Eloisa; Guilherme; Henrique; Izalorran; Matheus; Tiago; Yuri"?  Tem os antigos tb, José e Ana.

2023-09-19 17:43 UTC, IosBonaldi requested changes
- Bom 😀;
- Faz bom uso das constantes;

**CORREÇÃO NECESSÁRIA**
- Página de termos com rota definida mas conteúdo inexistente;

**RESSALVAS**
- Apesar de funcionar, deixo ressalvas com relação à como a página foi dinamizada, mais como dúvidas;
- Sugestões não imprescindíveis;

2023-09-19 17:43 UTC, IosBonaldi commented on src/pages/InfosPage.jsx
> -    const { title, content, showSidebar, showAccept, showNavTogglerMobile, showNavTogglerDesktop } = props;
- Há alguma vantagem que justifique a remoção do uso de props para título e conteúdo (ferramenta própria do framework utilizado e atualmente adotada em quase todo o projeto) em prol de checagens de rota manuais, não só nessa issue?
- Pontuo que é uma opção menos escalável (utilizar esse componente para outras páginas transformaria esta condicional em um switch bastante grande), de manutenção mais complexa (eventuais mudanças no endereço das rotas incorreria em ter que encontrar e alterar manualmente todas essas checagens);
- Anteriormente, a remoção das props havia incorrido na quebra da página de termos de uso. Aqui, novamente.
- A ideia de reutilizar o componente InfosPage para "termos" e "sobre o app" (agora também equipe) se deu em funções das páginas à época terem o mesmo formato: título único e conteúdo não formatado. Conforme as páginas vão se tornando distintas, talvez seja válido pensar em dividí-las novamente.

2023-09-29 01:57 UTC, m-piovesan approved these changes

2023-10-02 21:18 UTC, IosBonaldi approved these changes

2023-10-02 21:19 UTC, merged