#203 [FIX]: Modificado texto de senha incorreta e falha ao logar
VRI-UFPR/CienciaNaEscola pull request #204
Opened 2023-09-19 02:13 UTC by Gst-22

2023-09-19 15:26 UTC, IosBonaldi requested changes
- Bom;
- Correção necessária no tipo do input;

2023-09-19 15:26 UTC, IosBonaldi commented on src/pages/LoginPage.jsx
> +                            type="login"
```suggestion
                            type="text"
```
- _login_ não está na lista de tipos suportados para inputs HTML.

2023-09-22 14:18 UTC, YuriTobias approved these changes
- Ótimo!!

2023-09-25 01:27 UTC, IosBonaldi approved these changes

2023-09-25 18:57 UTC, merged