211 fix página de protocolos
VRI-UFPR/CienciaNaEscola pull request #214
Opened 2023-10-17 15:28 UTC by YuriTobias

- Verifiquem a responsividade! Cuidado: eu deixei o layout responsivo e não compatível com a home da dash, são coisas diferentes!

2023-10-18 12:46 UTC, tiagomb approved these changes

2023-10-19 14:20 UTC, m-piovesan requested changes
mano só não entendi seu comentário sobre estar responsivo mas não estar adaptado, por exemplo nesse print que eu coloquei aqui, esse era pra ser o comportamento mesmo ou tá bugado?

![image](https://github.com/VRI-UFPR/CienciaNaEscola/assets/97471131/b68df994-56fc-44b9-b00c-9314cdf9cd4e)

2023-10-21 10:21 UTC, YuriTobias commented
> mano só não entendi seu comentário sobre estar responsivo mas não estar adaptado, por exemplo nesse print que eu coloquei aqui, esse era pra ser o comportamento mesmo ou tá bugado?
> 
> ![image](https://user-images.githubusercontent.com/97471131/276646260-b68df994-56fc-44b9-b00c-9314cdf9cd4e.png)

Muito bem observado! Não era pra ficar desse jeito aí nope... Eu adicionei um padding vertical e acho que ficou mais agradável já :D.. Com relação ao meu comentário, é porque eu não me baseei no design da dash pra fazer a versão web dessa tela, porém, concidentemente ambas as telas vão ficar bem parecidas com um único diferencial de que a tela da dash deve receber um botão de criar novo protocolo na parte inferior e a sidebar estática à esquerda.. Fez sentido?

2023-10-24 00:06 UTC, m-piovesan commented
coisa linda yuriii

2023-10-24 00:06 UTC, m-piovesan approved these changes
showw!!

2023-10-25 00:04 UTC, merged