#209 [FIX]: profile page updated according to figma design
VRI-UFPR/CienciaNaEscola pull request #217
Opened 2023-10-18 01:55 UTC by m-piovesan

Guys, aguardo correções visto que algumas coisas deixei por enquanto meio sem funcionalidade pq não sabia direito como fazer

- como faço pra exibir os valores de nome, username, ..., no perfil?
- não sei como fazer esse botão de salvar mudanças funcional, por enquanto fiz estático

2023-10-18 12:44 UTC, tiagomb approved these changes

2023-10-19 01:48 UTC, m-piovesan commented
foi comentado em reunião agora que o botão de salvar será estático mesmo (enquanto não salvamos imagem), menos uma coisa para se preocupar por hora :)

2023-10-19 11:25 UTC, YuriTobias commented
> Guys, aguardo correções visto que algumas coisas deixei por enquanto meio sem funcionalidade pq não sabia direito como fazer
> 
> * como faço pra exibir os valores de nome, username, ..., no perfil?
> * não sei como fazer esse botão de salvar mudanças funcional, por enquanto fiz estático

Pra exibir os valores basta adicionar a propriedade "value" nos inputs e definir o value :D;

2023-10-19 11:51 UTC, YuriTobias requested changes
No arquivo Profile.jsx, além das sugestões de código:
- Remover imports de useState e useEffect;
- Remover a div que está comentada;
- Remover a div da atual linha 181 (do botão de alterar senha);

Sugestão: eu percebi que tu se importou em deixar a página responsiva e ficou show, o único ponto é que a responsividade pra versão web está um pouco diferente do que será apresentado na dash (de acordo com o figma), isso dito, fica a sugestão de tentar deixar a responsividade pra versão web em conformidade com o que está no figma pra dash, faz sentido? Em especial por motivos de padronização e consistência de telas, embora no fim elas vão possuir rotas diferentes, mas ainda acho válido hehe;

Obs: fiz muitas sugestões de código, tu pode (e deve) testar e avaliar se acha válido ou não aplicá-las de fato ;-)

Gostei que está bem responsiva e funcional (com exceção do botão de salvar que já foi discutido em reunião). Excelente!

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +// import { useNavigate } from 'react-router-dom';
```suggestion

```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
>  import ChangePassword from '../components/ChangePassword';
```suggestion

```
Pra dash esse componente vai ser útil, mas como vamos tirar o link de atualizar senha daqui (pelo menos por enquanto), então não precisamos mais desse import :D

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +    }
```suggestion
```
Aparentemente nada disso está sendo utilizado e a classe "text-pastel-blue" também não (mais acima)... Confere?

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
>      // const [name, setName] = useState('Seu nome');
```suggestion
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
>      const { showSidebar, allowEdit } = props;
```suggestion
    const { showSidebar, allowEdit } = props;
    const { user } = useContext(AuthContext);
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
>      useEffect(() => {
Pode remover esse useEffect e no if a seguir ao invés de email (que não tem mais), acho válido utilizar "user";

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
>                              <h2 className="fw-medium fs-5 m-0">Edite e adicione informações sobre você</h2>
```suggestion
                            <h6 className="fw-medium m-0">Edite e adicione informações sobre você</h6>
```
- Eu particularmente prefiro assim porque o texto não fica com quebra de linha (vide figma), mas dá uma olhada, se tu achar pequeno demais, basta trocar h6 por h5 e assim a gente nem precisa adicionar fs-something :D
- Na div acima "\<h1>...\</h1>", sou mais fã do pb-0 também (por conta do que está no figma)... Mas fica a teu critério daí :D

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +                                            hsl={[37, 98, 76]}
```suggestion
                                            hsl={[190, 46, 70]}
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
>                              <div className="col d-flex flex-column justify-content-center">
```suggestion
                            <div className="col-12 col-lg-9 d-flex flex-column justify-content-center">
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +                                            className="col-12 form-label profile-label fs-5 pb-2 pb-lg-0 pe-lg-5 mb-0"
```suggestion
                                            className="col-12 form-label profile-label fs-5 pb-0 pe-lg-5 mb-0"
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +                                            className="col-12 form-label profile-label fs-5 pb-2 pb-lg-0 pe-lg-5 mb-0"
```suggestion
                                            className="col-12 form-label profile-label fs-5 pb-0 pe-lg-5 mb-0"
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +                                            className="col-12 form-label profile-label fs-5 pb-2 pb-lg-0 pe-lg-5 mb-0"
```suggestion
                                            className="col-12 form-label profile-label fs-5 pb-0 pe-lg-5 mb-0"
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +                                            className="col-12 form-label profile-label fs-5 pb-2 pb-lg-0 pe-lg-5 mb-0"
```suggestion
                                            className="col-12 form-label profile-label fs-5 pb-0 pe-lg-5 mb-0"
```

2023-10-19 11:51 UTC, YuriTobias commented on src/pages/ProfilePage.jsx
> +                                        // onChange={(e) => setEmail(e.target.value)}
```suggestion
```

2023-10-20 12:33 UTC, m-piovesan commented on src/pages/ProfilePage.jsx
>                              <h2 className="fw-medium fs-5 m-0">Edite e adicione informações sobre você</h2>
nossa pq que tinha um fs-5 ali kkkkkkkkkkkkkkkkkk bem reparado mano, não tinha percebido

2023-10-20 12:36 UTC, m-piovesan commented on src/pages/ProfilePage.jsx
> +                                            hsl={[37, 98, 76]}
o problema de deixar com o light-blue é que fica ruim por causa do background, acho que vou deixar amarelo mesmo se pá 
![image](https://github.com/VRI-UFPR/CienciaNaEscola/assets/97471131/efad681f-d2bc-41c1-98d0-d1ac4c5df222)

2023-10-20 12:59 UTC, m-piovesan commented
corrigi a maioria das paradas, única coisa que não soube como fazer é a exibiçao dos atributos nome / username / instituição / papel no perfil, se alguém puder me dar uma luz eu agradeço :)

2023-10-20 14:04 UTC, YuriTobias commented
> corrigi a maioria das paradas, única coisa que não soube como fazer é a exibiçao dos atributos nome / username / instituição / papel no perfil, se alguém puder me dar uma luz eu agradeço :)

Então, uma vez que a API que está sendo utilizada não fornece alguns (a maioria) desses dados, acho que não precisa esquentar a cabeça com isso por enquanto :D

2023-10-20 14:06 UTC, YuriTobias approved these changes
- Excelente, muito bom!

2023-10-20 14:07 UTC, YuriTobias approved these changes

2023-10-24 00:03 UTC, merged