#268 [FEAT]: Ampliação e restrições do suporte a Markdown
VRI-UFPR/CienciaNaEscola pull request #272
Opened 2024-03-18 12:46 UTC by IosBonaldi

**Funcionalidades adicionadas**
- Restrições em Markdown para melhorar integração visual: cores e fontes restringidas, parágrafos padronizados em tamanho único (h1, h2, h3, h4, h5 e h6), imagens com bordas arredondadas e preenchimento horizontal completo;
- Encapsulamento do componente MarkdownText para facilitar inserções múltiplas;
- Inserção do suporte a Markdown nos componentes ProtocolInfo, CheckBoxInput, RadioButtonInput, ImageInput, SimpleTextInput e TextImageInput (que continua não sendo um input);

**Comentários**
- Suporte a Markdown não adicionado no componente SelectInput vide o mesmo ter alterações pendentes e código despadronizado;
- Suporte não adicionado em DateInput, TimeInput e Location input vide não caber seu uso;
- Suporte não adicionado em Weather vide o componente estar defasado;

2024-03-20 11:58 UTC, YuriTobias requested changes
Bom!

#### Possíveis correções:
- classe 'img-markdown';
- TextImageInput;
  - DefaultProps não funciona;
  - Componente que de fato não possui input;

#### Possível nova issue:
- Weather eh basicamente o RadioButtonInput que aceita como label uma imagem (file na api nova). Acho válido criar uma issue pra fazer as devidas correções em RadioButtonInput pra suportar esse tipo de componente e deletar o Weather que de fato está defasado.
- Obs: em teoria o mesmo serve para CheckBoxInput.

2024-03-20 11:58 UTC, YuriTobias commented on src/components/MarkdownText.jsx
> +    }
- Rodei a aplicação e aparentemente isso daqui não altera nada... A classe sequer eh utilizada nesse componente e as imagens do markdown, pelo que percebi, inerentemente, também não possuem essa classe.

2024-03-20 11:58 UTC, YuriTobias commented on src/components/MarkdownText.jsx
- Legal xD!

2024-03-20 11:58 UTC, YuriTobias commented on src/components/inputs/answers/ImageInput.jsx
> +    }
- ?

2024-03-20 11:58 UTC, YuriTobias commented on src/components/inputs/answers/RadioButtonInput.jsx
> +    }
- ?

2024-03-20 11:58 UTC, YuriTobias commented on src/components/inputs/answers/SimpleTextInput.jsx
> +    }
- ?

2024-03-20 11:58 UTC, YuriTobias commented on src/components/inputs/answers/TextImageInput.jsx
- Como esse componente não é um input não vejo motivos para não renomear... Aparentemente nenhum outro componente possui essa função específica de exibir texto + imagem sem input, então acho válido manter... Outra possível solução seria adaptar o SimpleTextInput, mas aí em alguns casos deixaria de ser input também, não sei se vale a pena daí...

2024-03-20 13:39 UTC, IosBonaldi commented
> Bom!
> 
> #### Possíveis correções:
> * classe 'img-markdown';
> * TextImageInput;
>   
>   * DefaultProps não funciona;
>   * Componente que de fato não possui input;
> 
> #### Possível nova issue:
> * Weather eh basicamente o RadioButtonInput que aceita como label uma imagem (file na api nova). Acho válido criar uma issue pra fazer as devidas correções em RadioButtonInput pra suportar esse tipo de componente e deletar o Weather que de fato está defasado.
> * Obs: em teoria o mesmo serve para CheckBoxInput.

- Há necessidade de checar se o leiaute para as imagens em RadioButton/CheckBoxInput será o mesmo de Weather visto que as imagens serão dinâminas e de tamanhos homogêneos (em sua maioria widescreen), tal como os textos.

2024-03-22 12:37 UTC, YuriTobias approved these changes
- Excelente;

2024-03-22 13:08 UTC, merged