#409 [FIX]: Remoção de protocolos offline em modo online
VRI-UFPR/CienciaNaEscola pull request #410
Opened 2024-08-11 23:38 UTC by IosBonaldi

2024-09-12 13:03 UTC, YuriTobias requested changes
- Ok! Segue o comportamento observado após a realização de testes com aplicações, resultado deve ser semelhante com protocolos: foi corrigida a questão de que agora se o usuário tem uma aplicação salva E tem internet, ele "refaz" o get da aplicação, ótimo; entretanto, se o usuário ficar offline e acessar a mesma aplicação, ele ainda visualiza a primeira aplicação salva no indexedDB, acredito que o ideal seja atualizar a aplicação salva no indexedDB também, não??

2024-09-12 13:51 UTC, IosBonaldi commented
> * Ok! Segue o comportamento observado após a realização de testes com aplicações, resultado deve ser semelhante com protocolos: foi corrigida a questão de que agora se o usuário tem uma aplicação salva E tem internet, ele "refaz" o get da aplicação, ótimo; entretanto, se o usuário ficar offline e acessar a mesma aplicação, ele ainda visualiza a primeira aplicação salva no indexedDB, acredito que o ideal seja atualizar a aplicação salva no indexedDB também, não??
> * Modelo de teste: carreguei uma aplicação (1ª vez), fiquei offline e entrei na aplicação, carregou certinho! Voltei a ficar online, fiz alterações no seed e atualizei o protocolo alterando o grupo de um dos itens; quando acessei a aplicação (2ª vez) com internet, a mesma estava atualizada (sem o item removido), fiquei offline e acessei novamente, o item estava lá!

- Você está correto. Vou checar;

2024-09-12 14:29 UTC, IosBonaldi commented
> * Ok! Segue o comportamento observado após a realização de testes com aplicações, resultado deve ser semelhante com protocolos: foi corrigida a questão de que agora se o usuário tem uma aplicação salva E tem internet, ele "refaz" o get da aplicação, ótimo; entretanto, se o usuário ficar offline e acessar a mesma aplicação, ele ainda visualiza a primeira aplicação salva no indexedDB, acredito que o ideal seja atualizar a aplicação salva no indexedDB também, não??
> * Modelo de teste: carreguei uma aplicação (1ª vez), fiquei offline e entrei na aplicação, carregou certinho! Voltei a ficar online, fiz alterações no seed e atualizei o protocolo alterando o grupo de um dos itens; quando acessei a aplicação (2ª vez) com internet, a mesma estava atualizada (sem o item removido), fiquei offline e acessei novamente, o item estava lá!



> * Ok! Segue o comportamento observado após a realização de testes com aplicações, resultado deve ser semelhante com protocolos: foi corrigida a questão de que agora se o usuário tem uma aplicação salva E tem internet, ele "refaz" o get da aplicação, ótimo; entretanto, se o usuário ficar offline e acessar a mesma aplicação, ele ainda visualiza a primeira aplicação salva no indexedDB, acredito que o ideal seja atualizar a aplicação salva no indexedDB também, não??
> * Modelo de teste: carreguei uma aplicação (1ª vez), fiquei offline e entrei na aplicação, carregou certinho! Voltei a ficar online, fiz alterações no seed e atualizei o protocolo alterando o grupo de um dos itens; quando acessei a aplicação (2ª vez) com internet, a mesma estava atualizada (sem o item removido), fiquei offline e acessei novamente, o item estava lá!

- Suponho que tenha sido corrigido. Em teoria, o que ocorria era uma incompatibilidade com a forma como o indexedDB avalia alterações: se a chave não muda, então o objeto é o mesmo. Aqui, nossa chave é o id, que nunca muda. Para fugir de soluções mais complexas, solucionei limpando o banco e reinserindo o item, em detrimento de tentar atualizá-lo. É uma solução que pode ser revista no futuro;

2024-09-30 12:15 UTC, YuriTobias approved these changes
Funcionando praticamente 100% conforme esperado! Faço uma ressalva somente quanto ao reconhecimento da aplicação local da primeira vez, pelo navegador eu tive que fazer um refresh da "tabela" applications para que a aplicação ficasse visível ao ficar offline, não sei se em dispositivos móveis o comportamento é o mesmo ou se ele atualiza automaticamente :(! No mais, se a aplicação foi atualizada e você tem acesso a internet, a aplicação também é atualizada, não está mais persistindo a aplicação local, ótimo!

2024-09-30 17:05 UTC, IosBonaldi commented
> Funcionando praticamente 100% conforme esperado! Faço uma ressalva somente quanto ao reconhecimento da aplicação local da primeira vez, pelo navegador eu tive que fazer um refresh da "tabela" applications para que a aplicação ficasse visível ao ficar offline, não sei se em dispositivos móveis o comportamento é o mesmo ou se ele atualiza automaticamente :(! No mais, se a aplicação foi atualizada e você tem acesso a internet, a aplicação também é atualizada, não está mais persistindo a aplicação local, ótimo!

- Em teoria o "refresh" contido nas dev tools deveria se referir apenas à visualização dentro da própria ferramenta dev tools. Se a aplicação não está percebendo a atualização da tabela, há um problema. Vou manter a PR aberta enquanto a questão permanecer pendente.

2024-10-01 15:57 UTC, merged