[ADD] Página AboutPage
VRI-UFPR/CienciaNaEscola pull request #45
Opened 2023-03-24 00:21 UTC by IosBonaldi

- Página AboutPage "Sobre o aplicativo";
- Código basicamente idêntico à TermsPage: levar em consideração possibilidade de mesclar ambas no futuro (mais atualizações de componente e menos redirecionamentos);

2023-03-24 11:17 UTC, EduardoMathiasSouza approved these changes

2023-03-24 19:13 UTC, YuriTobias requested changes
- Tem algumas (maioria acho) classes em styles que não foram utilizadas, creio que seja interessante removê-las;
- Nessa tela não é necessário o botão "aceitar";
- Como a navbar e a borda colorida fazem parte da maioria das telas, talvez dê pra deixá-las como absolute no app, nesse caso não seria necessário adicioná-las em todas as páginas, é algo a ser analisado;
- Tirando esses pequenos detalhes, o resto ficou show :D

2023-03-25 05:54 UTC, IosBonaldi commented
> * Tem algumas (maioria acho) classes em styles que não foram utilizadas, creio que seja interessante removê-las;
> * Nessa tela não é necessário o botão "aceitar";
> * Como a navbar e a borda colorida fazem parte da maioria das telas, talvez dê pra deixá-las como absolute no app, nesse caso não seria necessário adicioná-las em todas as páginas, é algo a ser analisado;
> * Tirando esses pequenos detalhes, o resto ficou show :D

- Estilos não usados são uma constante que se propagou conforme eu copiava código de um lado pro outro. Por ora resolvi nessa branch, mas eventualmente vou precisar resolver em todas as outras em algum momento mais amplo de refatoração;
- Botão removido;
- Como há páginas que não possuem, então infelizmente não dá pra fixar no App. Contudo, nessa linha e na do que foi citado na mensagem desse mesmo PR, muito provavelmente cabe mesclar componentes com características comuns (tais quais possuírem NavBar). Bom ponto;
- Resolvi o conflito;
- Fiz dismiss da review pra reavaliação;

2023-03-25 23:02 UTC, YuriTobias approved these changes
Sem ressalvas! Show!

2023-03-26 14:54 UTC, merged