4 componente navbar atualizado segundo novo leiaute
VRI-UFPR/CienciaNaEscola pull request #46
Opened 2023-03-24 00:37 UTC by IosBonaldi

- Componente NavBar de acordo com novo leiaute submetido no Figma: sem logo e com toggle à esquerda;

2023-03-24 11:17 UTC, EduardoMathiasSouza approved these changes

2023-03-24 19:22 UTC, YuriTobias requested changes
- As classes utilizadas para fazer a borda não estão sendo utilizadas (foi feito um comentário a respeito disso na pull request 41);

2023-03-25 06:07 UTC, IosBonaldi commented
> * As classes utilizadas para fazer a borda não estão sendo utilizadas (foi feito um comentário a respeito disso na pull request 41);

- A borda colorida foi, por alguma razão, comentada no [#b14a5893480ec3bf40117d28036ed78afd4520c1] e eventualmente removida no [#891ff4a3e5cf73a5f255a8bd491bcd10e843f22e] , provavelmente por engano. Reinserida;

2023-03-25 22:52 UTC, YuriTobias approved these changes
Só ver a questão do tabindex, tirando isso tudo ótimo!!

2023-03-25 22:52 UTC, YuriTobias commented on src/components/Navbar.jsx
>              </nav>
O console tá chorando aquele tabindex ali só (tá perguntando se não eh "tabIndex"), de resto tudo certo :D..

2023-03-26 15:02 UTC, IosBonaldi commented on src/components/Navbar.jsx
>              </nav>
- Teoricamente é. Por alguma razão, o meu não reclama, então peço que cheque se o erro persiste.

2023-03-26 15:10 UTC, YuriTobias commented on src/components/Navbar.jsx
>              </nav>
Agora ficou show!

2023-03-26 15:11 UTC, merged