#459 [FIX]: Responsividade da página de criação de grupos de usuários
VRI-UFPR/CienciaNaEscola pull request #468
Opened 2024-11-05 20:50 UTC by IosBonaldi

2024-11-06 11:56 UTC, YuriTobias requested changes
Deixei algumas sugestões! Não aprovei por conta da responsividade comprometer a visualização do botão na página de Criar/Editar usuário!

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateUserPage.jsx
> +                                        <div className="col-3 col-md-2">
```suggestion
                                        <div className="col-4 col-xl-3">
```
![image](https://github.com/user-attachments/assets/3fd8f5d8-6734-4c25-97d3-b70e93a89456)

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateUserPage.jsx
> +                            <div className="row justify-content-center font-barlow gx-0">
```suggestion
                            <div className="row justify-content-center justify-content-lg-start font-barlow gx-0">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateUserPage.jsx
> +                                <div className="col col-md-10 d-flex flex-column h-100 p-4">
```suggestion
                                <div className="col col-md-10 d-flex flex-column h-100 py-4">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/InstitutionPage.jsx
> +                                <div className="row d-flex justify-content-center justify-content-md-start pb-4">
```suggestion
                                <div className="row d-flex justify-content-center justify-content-lg-start pb-4">
```

Na linha 246 idem!

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateUserPage.jsx
> +                                            <div className="col-3 col-md-2">
```suggestion
                                            <div className="col-4 col-xl-3">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateUserPage.jsx
> +                                    <div className="row justify-content-center justify-content-lg-start gx-2 mt-0">
```suggestion
                                    <div className="row justify-content-center justify-content-lg-start gx-2">
```
Não vi razão aparente para manter esse mt-0, existe alguma?

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateClassroomPage.jsx
> +                            <div className="row justify-content-center font-barlow gx-0 mt-4">
```suggestion
                            <div className="row justify-content-center justify-content-lg-start font-barlow gx-0 mt-4">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateClassroomPage.jsx
> +                                <div className="col col-md-10 d-flex flex-column h-100 px-4">
```suggestion
                                <div className="col col-md-10 d-flex flex-column h-100 py-4">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateClassroomPage.jsx
> +                                    <div className="row justify-content-center justify-content-md-start gx-2 gy-4 mb-4">
```suggestion
                                    <div className="row justify-content-center justify-content-lg-start gx-2">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateClassroomPage.jsx
> +                                        <div className="col-3 col-md-2">
```suggestion
                                        <div className="col-4 col-xl-3">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateClassroomPage.jsx
> +                                            <div className="col-3 col-md-2">
```suggestion
                                            <div className="col-4 col-xl-3">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateApplicationPage.jsx
>                          <div className="row justify-content-center flex-grow-1 font-barlow gx-0">
```suggestion
                        <div className="row justify-content-center font-barlow gx-0">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateApplicationPage.jsx
> +                        <div className="row justify-content-center font-barlow gx-0 p-4">
```suggestion
                        <div className="row justify-content-center font-barlow gx-0">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateApplicationPage.jsx
> +                            <div className="col col-md-10 d-flex flex-column h-100">
```suggestion
                            <div className="col col-md-10 d-flex flex-column h-100 px-4">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateApplicationPage.jsx
> +                                <div className="row justify-content-center justify-content-md-start gx-2 gy-4">
```suggestion
                                <div className="row justify-content-center justify-content-lg-start gx-2 py-4">
```

2024-11-06 11:56 UTC, YuriTobias commented on src/pages/CreateApplicationPage.jsx
>                                      <div className="col-3 col-md-2">
```suggestion
                                    <div className="col-3 col-xl-2">
```
O mesmo na linha 954!

2024-11-07 13:07 UTC, IosBonaldi commented on src/pages/CreateUserPage.jsx
> +                                        <div className="col-3 col-md-2">
- Corrigido para `col-5 col-sm-3 col-xl-2`;

2024-11-07 13:09 UTC, IosBonaldi commented on src/pages/CreateUserPage.jsx
> +                            <div className="row justify-content-center font-barlow gx-0">
- Corrigido conforme sugestão;

2024-11-07 13:11 UTC, IosBonaldi commented on src/pages/InstitutionPage.jsx
> +                                <div className="row d-flex justify-content-center justify-content-md-start pb-4">
- Corrigido conforme sugestão;

2024-11-07 13:12 UTC, IosBonaldi commented on src/pages/CreateUserPage.jsx
> +                                            <div className="col-3 col-md-2">
- Corrigido para `col-5 col-sm-3 col-xl-2`;

2024-11-07 13:13 UTC, IosBonaldi commented on src/pages/CreateUserPage.jsx
> +                                    <div className="row justify-content-center justify-content-lg-start gx-2 mt-0">
- Não;

2024-11-07 13:16 UTC, IosBonaldi commented on src/pages/CreateClassroomPage.jsx
> +                                <div className="col col-md-10 d-flex flex-column h-100 px-4">
- Novamente, a `div` estava mal posicionada, o que provavelmente gerou a confusão. Aqui, o ideal também era `p-4`;

2024-11-07 20:17 UTC, IosBonaldi commented on src/pages/CreateClassroomPage.jsx
> +                                    <div className="row justify-content-center justify-content-md-start gx-2 gy-4 mb-4">
- Corrigido com revisão geral da página;

2024-11-07 20:17 UTC, IosBonaldi commented on src/pages/CreateClassroomPage.jsx
> +                                            <div className="col-3 col-md-2">
- Corrigido com revisão geral da página;

2024-11-07 20:17 UTC, IosBonaldi commented on src/pages/CreateApplicationPage.jsx
> +                        <div className="row justify-content-center font-barlow gx-0 p-4">
- Corrigido com revisão geral da página;

2024-11-07 20:18 UTC, IosBonaldi commented on src/pages/CreateApplicationPage.jsx
>                          <div className="row justify-content-center flex-grow-1 font-barlow gx-0">
- Corrigido com revisão geral da página;

2024-11-07 20:18 UTC, IosBonaldi commented on src/pages/CreateApplicationPage.jsx
> +                            <div className="col col-md-10 d-flex flex-column h-100">
- Corrigido com revisão geral da página;

2024-11-07 20:18 UTC, IosBonaldi commented on src/pages/CreateApplicationPage.jsx
> +                                <div className="row justify-content-center justify-content-md-start gx-2 gy-4">
- Corrigido com revisão geral da página;

2024-11-07 20:18 UTC, IosBonaldi commented on src/pages/CreateApplicationPage.jsx
>                                      <div className="col-3 col-md-2">
- Corrigido com revisão geral da página;

2024-11-12 00:13 UTC, YuriTobias approved these changes
- Excelente!

2024-11-12 00:47 UTC, merged