[ADD] página completa
VRI-UFPR/CienciaNaEscola pull request #47
Opened 2023-03-26 02:08 UTC by YuriTobias

- Página que deve aparecer quando o usuário clica no botão de ajuda;
- Nenhuma observação;

2023-03-26 11:34 UTC, EduardoMathiasSouza approved these changes

2023-03-26 15:41 UTC, IosBonaldi requested changes
- No geral, tudo certo em relação à estilização, fontes, etc;
- Ressalvo apenas a duplicação da ColoredBorder;

2023-03-26 15:41 UTC, IosBonaldi commented on src/pages/HelpPage.jsx
> +            <ColoredBorder />
```suggestion

```
- Conforme a ColoredBorder foi reintegrada à NavBar, não há necessidade de inserção explicita em outras páginas;

2023-03-27 01:46 UTC, JulianaZambon approved these changes

2023-03-27 16:55 UTC, IosBonaldi approved these changes

2023-03-27 17:27 UTC, merged