[ADD] página completa
VRI-UFPR/CienciaNaEscola pull request #48
Opened 2023-03-26 03:11 UTC by YuriTobias

- Sem observações;

2023-03-26 11:34 UTC, EduardoMathiasSouza approved these changes

2023-03-26 15:32 UTC, IosBonaldi requested changes
- No geral, tudo certo com aparência, fontes, etc;
- Ressalto apenas os bugs de espaçamento conforme sugestões;
- Falta da NavBar já conversada;
- Sugiro alterar o título da PR pra "19 página protocolo app" conforme padrão dos anteriores;

2023-03-26 15:32 UTC, IosBonaldi commented on src/pages/ProtocolPage.jsx
> +                <div className="row align-items-center">
```suggestion
                <div className="row align-items-center m-0">
```

- Por padrão, as rows do Bootstrap tem margens que eventualmente fazem ela "cair" da div pai. Nesse caso, o componente ficou torto pra esquerda. Zerar essas margens deve resolver;

2023-03-26 15:32 UTC, IosBonaldi commented on src/pages/ProtocolPage.jsx
> +                    <div className="col-3">
```suggestion
                    <div className="col-3 ps-0">
```
- A col da esquerda tem padding-left, mas a da direita não tem padding-right (até tem, mas os componentes internos tão violando);
- Pra não deixar o componente torto pra direita, acho mais fácil tirar o padding esquerdo do que descobrir a razão do direito ser violado (até pra padronizar com os outros componentes do form, que não tem padding);

2023-03-27 01:46 UTC, JulianaZambon approved these changes

2023-03-27 11:23 UTC, YuriTobias commented
> * No geral, tudo certo com aparência, fontes, etc;
> * Ressalto apenas os bugs de espaçamento conforme sugestões;
- Fiz alguns ajustes, creio que agora tenha ficado bom :)
> * Falta da NavBar já conversada;
- Foi adicionada ;)
> * Sugiro alterar o título da PR pra "19 página protocolo app" conforme padrão dos anteriores;
- Feito, tem razão!

2023-03-27 11:25 UTC, YuriTobias commented on src/pages/ProtocolPage.jsx
> +                    <div className="col-3">
Acabei diminuindo o tamanho dos componentes da coluna da direita e alterei os paddings e margens pra tentar padronizar, talvez agora esteja melhor :D

2023-03-27 17:26 UTC, IosBonaldi approved these changes

2023-03-27 17:27 UTC, merged