#485 [FIX]: Consistência da rolagem das páginas
VRI-UFPR/CienciaNaEscola pull request #487
Opened 2024-11-29 17:44 UTC by IosBonaldi

Esse pull request inclui várias atualizações para melhorar o layout e o estilo de várias páginas, bem como a adição de um novo componente `CustomContainer` para aprimorar a reutilização e a manutenção do código.

### Melhorias no layout e no estilo:

* [`src/components/ProtocolCarousel.jsx`](diffhunk://#diff-4c4b041ba0a46aa3e08af779fa7c7a87a1b91378894388eeb0c723fe82082d19L66-R66): Adicionado preenchimento aos itens do carrossel e ajustada a classe do contêiner principal do carrossel para melhorar o layout. [[1]](diffhunk://#diff-4c4b041ba0a46aa3e08af779fa7c7a87a1b91378894388eeb0c723fe82082d19L66-R66) [[2]](diffhunk://#diff-4c4b041ba0a46aa3e08af779fa7c7a87a1b91378894388eeb0c723fe82082d19L111-R111)
* [`src/components/ProtocolList.jsx`](diffhunk://#diff-c14f75f6a7980763412cd29e61027449a1adf9bcd1c5675fa358b566a3b1150dL68-R68): Adição da classe `overflow-hidden` ao contêiner de lista para evitar problemas de transbordamento.
* [`src/pages/ApplicationsPage.jsx`](diffhunk://#diff-916eef37efa9e8ed763477376594b83ffd4da6fe1be638e549c95ee2e918bfaeR27): Atualização do layout para usar o novo componente `CustomContainer` e ajuste de vários nomes de classes para melhor alinhamento e capacidade de resposta. [[1]](diffhunk://#diff-916eef37efa9e8ed763477376594b83ffd4da6fe1be638e549c95ee2e918bfaeR27) [[2]](diffhunk://#diff-916eef37efa9e8ed763477376594b83ffd4da6fe1be638e549c95ee2e918bfaeL41-R47) [[3]](diffhunk://#diff-916eef37efa9e8ed763477376594b83ffd4da6fe1be638e549c95ee2e918bfaeR59-R62) [[4]](diffhunk://#diff-916eef37efa9e8ed763477376594b83ffd4da6fe1be638e549c95ee2e918bfaeL117-R147) [[5]](diffhunk://#diff-916eef37efa9e8ed763477376594b83ffd4da6fe1be638e549c95ee2e918bfaeL148-R181)
* [`src/pages/InfosPage.jsx`](diffhunk://#diff-f248e7f42012e772bd922285e79702ca63d7a5680755134e813c18467bb63f0dR23): Refatoramos o layout para usar o `CustomContainer` e melhoramos o estilo dos botões e da área de conteúdo principal. [[1]](diffhunk://#diff-f248e7f42012e772bd922285e79702ca63d7a5680755134e813c18467bb63f0dR23) [[2]](diffhunk://#diff-f248e7f42012e772bd922285e79702ca63d7a5680755134e813c18467bb63f0dL81-R84) [[3]](diffhunk://#diff-f248e7f42012e772bd922285e79702ca63d7a5680755134e813c18467bb63f0dL92-R115)
* [`src/pages/InstitutionsPage.jsx`](diffhunk://#diff-9d4e7b3351fb92537bcf0e6c010bacf2aeaffb4ef828ae1b31661c0a7b5553c2R26): Atualização do layout para usar o `CustomContainer` e ajuste do layout para melhor alinhamento e capacidade de resposta. [[1]](diffhunk://#diff-9d4e7b3351fb92537bcf0e6c010bacf2aeaffb4ef828ae1b31661c0a7b5553c2R26) [[2]](diffhunk://#diff-9d4e7b3351fb92537bcf0e6c010bacf2aeaffb4ef828ae1b31661c0a7b5553c2R41-R57) [[3]](diffhunk://#diff-9d4e7b3351fb92537bcf0e6c010bacf2aeaffb4ef828ae1b31661c0a7b5553c2L104-R134) [[4]](diffhunk://#diff-9d4e7b3351fb92537bcf0e6c010bacf2aeaffb4ef828ae1b31661c0a7b5553c2L132-R159)

### Reutilização do código:

* [`src/components/CustomContainer.jsx`](diffhunk://#diff-3fb2a0b58ef25f9429cb91b94b11a8c0bfffcf97a923ae6c0f5999ed8128bb52L14-R14): Introduzimos um novo componente `CustomContainer` para padronizar a estrutura do layout em diferentes páginas. [[1]](diffhunk://#diff-3fb2a0b58ef25f9429cb91b94b11a8c0bfffcf97a923ae6c0f5999ed8128bb52L14-R14) [[2]](diffhunk://#diff-3fb2a0b58ef25f9429cb91b94b11a8c0bfffcf97a923ae6c0f5999ed8128bb52R23)

### Outras alterações:

* [`src/pages/ProfilePage.jsx`](diffhunk://#diff-bf917061450d470046fa9145f961da20c6e9eec459a7cba2acc9d6690d389142R24): Adição da importação `CustomContainer` para melhorar a consistência do código. [[1]](diffhunk://#diff-bf917061450d470046fa9145f961da20c6e9eec459a7cba2acc9d6690d389142R24) [[2]](diffhunk://#diff-bf917061450d470046fa9145f961da20c6e9eec459a7cba2acc9d6690d389142L63)

2025-02-04 00:40 UTC, YuriTobias requested changes
- Muito bom! Apenas algumas correções sugeridas e uma dúvida comentada em código.

2025-02-04 00:40 UTC, YuriTobias commented on src/pages/InstitutionsPage.jsx
> +                            <div class="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```suggestion
                            <div className="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```

Esse overflow sem "lg" não funciona em telas menores que o breakpoint do lg, alguma razão para tal?

2025-02-04 00:40 UTC, YuriTobias commented on src/pages/ApplicationsPage.jsx
> +                                <div class="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```suggestion
                                <div className="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```

2025-02-04 00:40 UTC, YuriTobias commented on src/pages/ApplicationsPage.jsx
> +                                <div class="row flex-grow-1 overflow-y-hidden pb-lg-4 g-4">
```suggestion
                                <div className="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```

A ausência desse "lg" torna essa div inconsistente com o que seria a mesma div caso fosse dash.

2025-02-04 00:40 UTC, YuriTobias commented on src/pages/ProtocolsPage.jsx
> +                            <div class="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```suggestion
                            <div className="row flex-grow-1 overflow-lg-y-hidden pb-lg-4 g-4">
```

2025-02-06 18:57 UTC, IosBonaldi commented
- Propriedades de tag erroneamente nomeadas foram corrigidas;
- Questão do não funcionamento da classe overflow sem breakpoint se deve ao fato de seu comportamento depender de outras classes também dotadas de breakpoint. Assim, para alterá-lo é necessário remover também os breakpoints das respectivas classes (geralmente alguns h-lg-100, podendo haver outros);

2025-02-06 18:58 UTC, IosBonaldi commented on src/pages/ApplicationsPage.jsx
> +                                <div class="row flex-grow-1 overflow-y-hidden pb-lg-4 g-4">
Não entendi;

2025-02-10 19:49 UTC, YuriTobias approved these changes

2025-02-14 20:56 UTC, merged