54 fix uniformizar e corrigir implementação do helpbutton
VRI-UFPR/CienciaNaEscola pull request #55
Opened 2023-03-27 23:32 UTC by IosBonaldi

2023-03-31 13:51 UTC, YuriTobias requested changes
Show! Só mudar o nome da function mesmo e tudo certo...

2023-03-31 13:51 UTC, YuriTobias commented on src/components/HelpButton.jsx
> +function HomeArrows(props) {
HomeArrows 👀??

2023-03-31 13:51 UTC, YuriTobias commented on src/components/HelpButton.jsx
> +                <img src={helpIcon} alt="Ícone" className="w-100"></img>
Se pá que dá pra melhorar esse alt (ex: Ícone de ajuda)... Só uma sugestão mesmo...

2023-03-31 13:51 UTC, YuriTobias commented on src/components/HelpButton.jsx
> +export default HomeArrows;
HomeArrows 👀

2023-04-03 10:17 UTC, EduardoMathiasSouza commented on src/components/HelpButton.jsx
> +function HomeArrows(props) {
HomeArrows 🤟

2023-04-03 10:17 UTC, EduardoMathiasSouza commented on src/pages/TermsPage.jsx
> -                                <img src={helpIcon} alt="Ícone" className="w-100"></img>
Alt pode seguir o padrão em Inglês, daí so colocar alt=HelpIcon tbm, na minha visao

2023-04-04 14:04 UTC, EduardoMathiasSouza approved these changes

2023-04-12 13:58 UTC, merged