43 componente imagem app
VRI-UFPR/CienciaNaEscola pull request #58
Opened 2023-04-04 03:18 UTC by IosBonaldi

2023-04-04 03:19 UTC, IosBonaldi commented on public/index.html
> -  <head>
- Não alterei index.html: são apenas questões de indentação vide o arquivo estar fora do escopo do script de indentação automática;

2023-04-12 14:05 UTC, YuriTobias requested changes
- Tirando as observações, tudo certo! Ficou show!

2023-04-12 14:05 UTC, YuriTobias commented on src/components/TextImageInput.jsx
> +function TextImageInput({ options = [], image }) {
A função está recebendo "options", mas aparentemente elas não estão sendo utilizadas, tá certo isso??

2023-04-12 14:09 UTC, IosBonaldi commented on src/components/TextImageInput.jsx
> +function TextImageInput({ options = [], image }) {
- Nada relacionado aos parâmetros recebidos é certo. Tudo provisório/rascunho e que pode (ou muito provavelmente não), persistirem conforme evolução da #61;

2023-04-12 14:23 UTC, merged